[package]
name = "exercicio_temperatura_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
inquire = "0.6"     # menus, setinhas, input UX profissional
serde = { version = "1.0", features = ["derive"] } # pode ser Ãºtil depois
serde_json = "1.0"